// <auto-generated />
using System;
using COService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace COService.Infrastructure.Migrations
{
    [DbContext(typeof(COServiceDbContext))]
    [Migration("20250127163320_UpdateAbonnementModel")]
    partial class UpdateAbonnementModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Le snapshot sera mis à jour automatiquement par EF Core après l'application de la migration
#pragma warning restore 612, 618
        }
    }
}

