// <auto-generated />
using System;
using COService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace COService.Infrastructure.Migrations
{
    [DbContext(typeof(COServiceDbContext))]
    partial class COServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("COService.Domain.Entities.Abonnement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("CertificateId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("certificate_id");

                    b.Property<DateTime?>("CreeLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreeLe");

                    b.Property<string>("CreePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreePar");

                    b.Property<string>("Exportateur")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("exportateur");

                    b.Property<string>("FactureNo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("factureNo");

                    b.Property<string>("Formule")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("formule");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ModifiePar");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifierLe");

                    b.Property<string>("Numero")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("numero");

                    b.Property<string>("Partenaire")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("partenaire");

                    b.Property<string>("Statut")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Statut");

                    b.Property<string>("TypeCO")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("type_co");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId")
                        .IsUnique()
                        .HasFilter("[certificate_id] IS NOT NULL");

                    b.ToTable("abonnements", (string)null);
                });

            modelBuilder.Entity("COService.Domain.Entities.CertificatOrigine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("AbonnementId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("abonnement_id");

                    b.Property<string>("CertificateNo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CertificateNo");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreeLe");

                    b.Property<string>("CreePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreePar");

                    b.Property<Guid?>("DocumentsId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("documents_id");

                    b.Property<string>("Exportateur")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Exportateur");

                    b.Property<string>("Formule")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Formule");

                    b.Property<string>("Mandataire")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Mandataire");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ModifiePar");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifierLe");

                    b.Property<string>("Navire")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("navire");

                    b.Property<string>("Observation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Observation");

                    b.Property<string>("Partenaire")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Partenaire");

                    b.Property<string>("PaysDestination")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("PaysDestination");

                    b.Property<string>("PortCongo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("PortCongo");

                    b.Property<string>("PortSortie")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("PortSortie");

                    b.Property<string>("ProductsRecipientAddress1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ProductsRecipientAddress1");

                    b.Property<string>("ProductsRecipientAddress2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ProductsRecipientAddress2");

                    b.Property<string>("ProductsRecipientName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ProductsRecipientName");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Statut");

                    b.Property<Guid?>("TypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TypeId");

                    b.HasKey("Id");

                    b.HasIndex("AbonnementId");

                    b.HasIndex("CertificateNo")
                        .IsUnique()
                        .HasDatabaseName("IX_certificates_CertificateNo");

                    b.HasIndex("TypeId");

                    b.ToTable("certificates", null, t =>
                        {
                            t.HasCheckConstraint("CK_certificates_Statut", "Statut IN ('Élaboré', 'Soumis', 'Contrôlé', 'Approuvé', 'Validé')");
                        });
                });

            modelBuilder.Entity("COService.Domain.Entities.CertificateLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CertificateId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("certificate_id");

                    b.Property<DateTime?>("CreeLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreeLe");

                    b.Property<string>("CreePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreePar");

                    b.Property<string>("HSCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HSCode");

                    b.Property<string>("LineFOBValue")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LineFOBValue");

                    b.Property<string>("LineGrossWeight")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LineGrossWeight");

                    b.Property<string>("LineNatureOfProduct")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("LineNatureOfProduct");

                    b.Property<string>("LineNetWeight")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LineNetWeight");

                    b.Property<string>("LineQuantity")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LineQuantity");

                    b.Property<string>("LineUnits")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LineUnits");

                    b.Property<string>("LineVolume")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LineVolume");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ModifiePar");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifierLe");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId");

                    b.ToTable("certificate_lines", (string)null);
                });

            modelBuilder.Entity("COService.Domain.Entities.CertificateType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CreeLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreeLe");

                    b.Property<string>("CreePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreePar");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("designation");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ModifiePar");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifierLe");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_certificate_types_code");

                    b.ToTable("certificate_types", (string)null);
                });

            modelBuilder.Entity("COService.Domain.Entities.CertificateValidation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CertificateId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("certificate_id");

                    b.Property<string>("Commentaire")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Commentaire");

                    b.Property<DateTime?>("CreeLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreeLe");

                    b.Property<string>("CreePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreePar");

                    b.Property<string>("Etape")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Etape");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ModifiePar");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifierLe");

                    b.Property<string>("RoleVisa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("RoleVisa");

                    b.Property<string>("VisaPar")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("VisaPar");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId");

                    b.ToTable("certificate_validations", (string)null);
                });

            modelBuilder.Entity("COService.Domain.Entities.Commentaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CertificateId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("certificate_id");

                    b.Property<string>("CommentaireText")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Commentaire");

                    b.Property<DateTime?>("CreeLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreeLe");

                    b.Property<string>("CreePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreePar");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ModifiePar");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifierLe");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId");

                    b.ToTable("commentaires", (string)null);
                });

            modelBuilder.Entity("COService.Domain.Entities.Abonnement", b =>
                {
                    b.HasOne("COService.Domain.Entities.CertificatOrigine", "Certificate")
                        .WithOne()
                        .HasForeignKey("COService.Domain.Entities.Abonnement", "CertificateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Certificate");
                });

            modelBuilder.Entity("COService.Domain.Entities.CertificatOrigine", b =>
                {
                    b.HasOne("COService.Domain.Entities.Abonnement", "Abonnement")
                        .WithMany("Certificats")
                        .HasForeignKey("AbonnementId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("COService.Domain.Entities.CertificateType", "Type")
                        .WithMany("Certificats")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Abonnement");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("COService.Domain.Entities.CertificateLine", b =>
                {
                    b.HasOne("COService.Domain.Entities.CertificatOrigine", "CertificatOrigine")
                        .WithMany("CertificateLines")
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CertificatOrigine");
                });

            modelBuilder.Entity("COService.Domain.Entities.CertificateValidation", b =>
                {
                    b.HasOne("COService.Domain.Entities.CertificatOrigine", "CertificatOrigine")
                        .WithMany("CertificateValidations")
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CertificatOrigine");
                });

            modelBuilder.Entity("COService.Domain.Entities.Commentaire", b =>
                {
                    b.HasOne("COService.Domain.Entities.CertificatOrigine", "CertificatOrigine")
                        .WithMany("Commentaires")
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CertificatOrigine");
                });

            modelBuilder.Entity("COService.Domain.Entities.Abonnement", b =>
                {
                    b.Navigation("Certificats");
                });

            modelBuilder.Entity("COService.Domain.Entities.CertificatOrigine", b =>
                {
                    b.Navigation("CertificateLines");

                    b.Navigation("CertificateValidations");

                    b.Navigation("Commentaires");
                });

            modelBuilder.Entity("COService.Domain.Entities.CertificateType", b =>
                {
                    b.Navigation("Certificats");
                });
#pragma warning restore 612, 618
        }
    }
}
